<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Hugo-Tech-175" failures="1" tests="5" name="Test" time="462.386" errors="0" timestamp="2022-01-14T01:37:12 WAT">
  <testcase classname="testCases.LoginInvalidTest" name="loginInvalid" time="42.594"/>
  <testcase classname="testCases.LogoutTest" name="logout" time="73.239"/>
  <testcase classname="testCases.LoginTest" name="login1" time="80.113"/>
  <testcase classname="testCases.NewMedicationTest" name="newMedication" time="84.401">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at testCases.NewMedicationTest.newMedication(NewMedicationTest.java:36)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- newMedication -->
  <testcase classname="testCases.NewRequestTest" name="newRequest" time="460.04"/>
</testsuite> <!-- Test -->
